# Generated by Django 6.1.1 on 2026-09-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_listed',
            field=models.BooleanField(default=True, help_text='Check to hide the post'),
        ),
    ]
